
############### Command History ###############
ISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

############### Load Alias ###############
source ~/.aliasrc

############### Loads Pluggins ###############
source /usr/share/powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/autojump/autojump.zsh
